name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  BACKEND_SERVICE: ecommerce-backend
  FRONTEND_SERVICE: ecommerce-frontend

jobs:
  deploy:
    name: Build & Deploy Backend and Frontend to Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up gcloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    # ──────── BACKEND ────────
    - name: Build and Push Backend Image
      run: |
        gcloud builds submit backend \
          --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }}

    - name: Deploy Backend to Cloud Run
      run: |
        gcloud run deploy ${{ env.BACKEND_SERVICE }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_SERVICE }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated

    # ──────── FRONTEND ────────
    - name: Build and Push Frontend Image
      run: |
        gcloud builds submit frontend \
          --tag gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }}

    - name: Deploy Frontend to Cloud Run
      run: |
        gcloud run deploy ${{ env.FRONTEND_SERVICE }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_SERVICE }} \
          --region ${{ env.REGION }} \
          --platform managed \
          --allow-unauthenticated
